### ISSUE TITLE
Neck trim mode not parsed correctly

### ISSUE THREAD

**Issue by cookpa** [willtack/antsct-aging-fw#2]
Hi @willtack, I've found that gear runs with antsct-aging-fw_0.3.1_0.3.3 do not end up with the correct masking option.

I suspect the problem is here

https://github.com/willtack/antsct-aging-fw/blob/ac8cfd642d58d1334ac402afd52d4b9d506c931f/prepare_run.py#L102

I'm not sure if the Flywheel config manager allows partial matching. 

In this example, the gear config is correct

<img width="939" alt="image" src="https://user-images.githubusercontent.com/611507/155601784-adf7d7ad-e571-4c52-9ad0-9f3161039051.png">

but `antsct_run.sh` contains `--trim-neck-mode None` - I think this is the Python None and not a string "none" from the manifest.

**Comment by willtack** [comment]
Hm okay so were you trying to run it using the SDK, then? Maybe it would be better to have a raw string input rather than the three option drop down menu.

**Comment by cookpa** [comment]
Yeah, I think it was via the SDK, right @jeffrey-phillips?

**Comment by cookpa** [comment]
But I ran a session interactively and it had the same issue. You might need to get "trim-neck-mode". Many arg parsers will accept partial matches but I don't know if Flywheel's gear context does.

https://github.com/willtack/antsct-aging-fw/blob/ac8cfd642d58d1334ac402afd52d4b9d506c931f/manifest.json#L122-L132

**Comment by jeffrey-phillips** [comment]
Yes, the vast majority of our jobs were run via SDK. Maybe <50 were run through the GUI here and there by coordinators or myself, but I wouldn't know which ones.

**Comment by jeffrey-phillips** [comment]
These jobs were generally run with the run_antsct_aging function in https://raw.githubusercontent.com/ftdc-picsl/Flywheel_python_sdk/master/fwtools.py. We do try to pass the mask option there:

    config = {
        'denoise': True,
        'num-threads': numThreads,
        'pad-input': 10,
        'run-quick': runQuick,
        'trim-neck-mode': 'mask'
    }

**Comment by willtack** [comment]
Okay, thanks Phil and Jeff. I fixed the line to make it an exact match: 
https://github.com/willtack/antsct-aging-fw/blob/7cecc512f831647d486207c61b38078c5906af32/prepare_run.py#L102

And pushed to Flywheel. Let me know if this works.

**Comment by cookpa** [comment]
Thanks, what's the gear version? I don't see any update to "FTDC ANTs Cortical Thickness"

**Comment by willtack** [comment]
Ah, looks like the push failed. Sorry about that. Uploaded again, version 0.3.2_0.3.3

**Comment by cookpa** [comment]
Thanks, I'm testing it. 

@jeffrey-phillips we will need to ensure any submission SDK scripts specifically use version 0.3.1_0.3.3 for consistency.

**Comment by cookpa** [comment]
OK, I can see it works now. Thanks
